### ISSUE TITLE
Error: pokeUrl is not defined.

### ISSUE THREAD

**Issue by FarahZaqout** [foundersandcoders/mc-promise-me-this#15]
https://github.com/foundersandcoders/mc-promise-me-this/blob/9ed3e7b39df50d47744f92137b7c7afe8ffc3c0f/solution.js#L47-L49

I think this is a typo here where it should be ```makePokeUrl(params)``` instead.

**Comment by astroash** [comment]
@farahzaqout yup, you are correct. The name of the function was changed in the last PR. 

PR welcome 😊
